#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

current_branch=`git rev-parse --abbrev-ref HEAD`
if [[ $current_branch =~ master|main|develop ]]; then
    message="Please don't push directly to $current_branch."
    echo "\033[1;31mERROR: $message\033[0m";
    exit 1
fi

repo_dir=`git rev-parse --show-toplevel`

message="[Policy] Trying to build project..."
echo "\033[1;34mInfo: $message\033[0m"

npm run build

if [ $? -eq 1 ]; then
    message="[Policy] Project build failed, please check and fix your code."
    echo "\033[1;31mERROR: $message\033[0m";
    exit 1
else
    message="[Policy] Done."
    echo "\033[1;32mOK: $message\033[0m"
    exit 0
fi
